version: '3'
services:
    unigine_test_nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - unigine_test_php
        networks:
            - unigine_test_network
    unigine_test_php:
        build: ./images/php
        links:
            - unigine_test_mysql
        volumes:
            - ./www:/var/www
        networks:
            - unigine_test_network
    unigine_test_mysql:
        build: ./images/mysql
        ports:
            - "3306:3306"
        volumes:
         - ./etc/mysql:/etc/mysql
         - ./logs/mysql:/var/log/mysql
         - ./mysql:/var/lib/mysql
         - ./mysql-files:/var/lib/mysql-files
         - ./data/url_shortener.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - unigine_test_network
networks:
    unigine_test_network:
